import "../index.css";

type DisclaimerProps = {
  onBack: () => void;
};

function Disclaimer({ onBack }: DisclaimerProps) {
  return (
    <main className="legal-page">
      <div className="legal-container">

        {/* Header */}
        <div className="legal-header">
          <button className="back-button" onClick={onBack}>
            ← Back
          </button>

          <span className="legal-label">
            LEGAL
          </span>
        </div>

        {/* Title */}
        <section className="legal-hero">
          <div className="legal-icon">⚖️</div>

          <h1>Disclaimer & Legal Notice</h1>

          <p>
            Please read this before relying on anything produced by
            Stupid AI.
          </p>
        </section>

        {/* Important notice */}
        <div className="legal-warning">
          <strong>⚠️ Important</strong>

          <p>
            Stupid AI is intentionally designed to generate absurd,
            incorrect, and humorous responses. Its output may be
            factually wrong, misleading, nonsensical, or completely
            unrelated to reality.
          </p>
        </div>

        {/* 1 */}
        <section className="legal-section">
          <h2>1. Nature of the service</h2>

          <p>
            Stupid AI is an independent experimental software project
            created for educational, research, development, and
            entertainment purposes.
          </p>

          <p>
            The service is not intended to provide authoritative
            information or professional advice.
          </p>
        </section>

        {/* 2 */}
        <section className="legal-section">
          <h2>2. Do not rely on AI-generated answers</h2>

          <p>
            Responses generated by Stupid AI should not be treated as
            factual or reliable information.
          </p>

          <p>
            In particular, do not use Stupid AI as a substitute for
            qualified professional advice concerning:
          </p>

          <ul>
            <li>Medical or health decisions</li>
            <li>Legal matters</li>
            <li>Financial or investment decisions</li>
            <li>Safety-critical situations</li>
            <li>Academic or professional decisions</li>
            <li>Emergency situations</li>
          </ul>

          <p>
            Always verify important information using appropriate
            authoritative sources or qualified professionals.
          </p>
        </section>

        {/* 3 */}
        <section className="legal-section">
          <h2>3. Intentionally incorrect output</h2>

          <p>
            Unlike conventional AI assistants, Stupid AI is explicitly
            instructed to produce deliberately incorrect and absurd
            responses.
          </p>

          <p>
            A response that appears confident, detailed, or convincing
            should not be interpreted as evidence that the information
            is correct.
          </p>
        </section>

        {/* 4 */}
        <section className="legal-section">
          <h2>4. AI and third-party services</h2>

          <p>
            Stupid AI uses third-party artificial intelligence services
            to generate responses.
          </p>

          <p>
            Because these services are operated by third parties, their
            availability, performance, policies, pricing, models, and
            technical behavior may change without notice.
          </p>

          <p>
            Stupid AI does not guarantee that responses generated by
            third-party AI systems will be available, accurate, safe,
            consistent, or uninterrupted.
          </p>
        </section>

        {/* 5 */}
        <section className="legal-section">
          <h2>5. Availability</h2>

          <p>
            Stupid AI is provided on an experimental basis. The service
            may be modified, interrupted, restricted, suspended, or
            discontinued at any time.
          </p>

          <p>
            No guarantee is made that the service will always be
            available or operate without errors.
          </p>
        </section>

        {/* 6 */}
        <section className="legal-section">
          <h2>6. No warranties</h2>

          <p>
            To the extent permitted by applicable law, Stupid AI is
            provided on an "as is" and "as available" basis without
            warranties of any kind.
          </p>

          <p>
            This includes, without limitation, warranties concerning
            accuracy, reliability, availability, fitness for a
            particular purpose, or suitability for a particular use.
          </p>
        </section>

        {/* 7 */}
        <section className="legal-section">
          <h2>7. Limitation of liability</h2>

          <p>
            To the maximum extent permitted by applicable law, the
            creator of Stupid AI will not be responsible for losses,
            damages, or consequences arising from reliance on,
            inability to use, or use of information generated by the
            service.
          </p>

          <p>
            This limitation does not apply where such limitation is
            prohibited by applicable law.
          </p>
        </section>

        {/* 8 */}
        <section className="legal-section">
          <h2>8. User responsibility</h2>

          <p>
            You are responsible for deciding whether information
            generated by Stupid AI is appropriate for your intended
            purpose.
          </p>

          <p>
            You should independently verify any information before
            acting on it, particularly when the consequences of being
            wrong could be significant.
          </p>
        </section>

        {/* 9 */}
        <section className="legal-section">
          <h2>9. User-provided content</h2>

          <p>
            Do not submit passwords, authentication credentials,
            financial account information, highly sensitive personal
            information, or other information that you would not want
            processed by an external AI service.
          </p>

          <p>
            Information submitted to the service may be transmitted to
            the third-party AI provider required to generate a response.
          </p>
        </section>

        {/* 10 */}
        <section className="legal-section">
          <h2>10. Intellectual property</h2>

          <p>
            Stupid AI is an independent project and is not affiliated
            with, sponsored by, or endorsed by OpenAI, Groq, or any
            other third-party AI provider.
          </p>

          <p>
            Third-party names, trademarks, logos, and technologies
            referenced by the project remain the property of their
            respective owners.
          </p>

          <p>
            The name "Stupid AI" is used to describe this independent
            project and its intentionally humorous purpose.
          </p>
        </section>

        {/* 11 */}
        <section className="legal-section">
          <h2>11. Prohibited use</h2>

          <p>
            You should not use Stupid AI to generate, facilitate, or
            assist with unlawful activity, harm to others, or other
            activity prohibited by applicable law or the policies of
            the underlying AI provider.
          </p>
        </section>

        {/* 12 */}
        <section className="legal-section">
          <h2>12. Changes to this notice</h2>

          <p>
            This disclaimer may be updated as the project changes.
            Continued use of the service after an update may constitute
            acceptance of the revised notice where applicable.
          </p>
        </section>

        {/* Final warning */}
        <section className="legal-final">
          <div className="legal-final-icon">
            🍌
          </div>

          <h2>
            In short: don't trust the banana.
          </h2>

          <p>
            Stupid AI is built to be wrong. If something actually
            matters, verify it somewhere that isn't deliberately
            trying to give you a stupid answer.
          </p>
        </section>

        {/* Footer */}
        <footer className="legal-footer">
          <p>
            Stupid AI · Independent experimental student project
          </p>

          <button
            className="back-button"
            onClick={onBack}
          >
            ← Back to Stupid AI
          </button>
        </footer>

      </div>
    </main>
  );
}

export default Disclaimer;